name: mm_swipeable
description: MmSwipeable is a Flutter package that provides a widget for enabling swipe actions in both left and right directions.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
